### PR TITLE
Edited lvm_volume_group(:extend) and lvm_logical_volume(:resize) issues

### PR DESCRIPTION
**Pull request by hulu1522**
`lvm_volume_group` would create logical volumes correctly.  When the `extend` options were added there was no way for an internal `logical_volume` resource to resize.  It will now execute the `:resize` action on logical volumes when the logical volume group is extended.

Example code:
```ruby
lvm_volume_group 'test' do
  physical_volumes ['/dev/vdc', '/dev/vdd']
  action [:create, :extend]

  logical_volume 'main' do
    size '100%FREE'
    filesystem 'ext4'
    mount_point '/srv'
    take_up_free_space true
  end
end
```

There was also an issue with the `:resize` action where `lv.path` didn't exist and would fail during run.  I changed `lv.path` to `device_name` which is they way it is used in the `:create` resource.

### CODE REVIEW

**Comment by b-dean** [comment]
@someara and @jtimberman, any chance of this getting merged and there being a proper release of this resizing/extending stuff (with the version actually uploaded to the supermarket)? I don't really understand what @mgolfieri was saying about version 1.2.3, but since the resizing stuff was in 1.3.0 and this kind of fixes a bug with it, I'd think 1.3.2 would be more appropriate (IMHO).

Anyway, I'd just like to see this get merged so we can use it. :smile:

**Comment by mgolfieri** [comment]
Just meant that at the time the fix was in HEAD only, so I had to specify the hash to get it:

cookbook 'lvm', git: 'https://github.com/opscode-cookbooks/lvm.git', reference: '3243e6098e2adaca3c4e46fc7cc01ad4a7fcd094'

Which implicitly locked it to that.  Going > 1.2.2 (whatever numbering) will do, txs!

**Comment by juliandunn** [comment]
Sorry for the delay. This generally LGTM -- @b-dean and @mgolfieri are you running with the code in this branch? Is it a :+1: from you?

**Comment by b-dean** [comment]
I've been using it and it seems fine to me

**Comment by juliandunn** [comment]
Merging then, thanks

**Comment by hulu1522** [comment]
Nice, thanks for merging this.  Is it possible to have an updated version and pushed to the supermarket?  Thanks.  :)

**Comment by juliandunn** [comment]
@hulu1522 Yep, I'm gonna do some minimal cleanup and get the tests running again & then will do a release.

**Comment by hulu1522** [comment]
@juliandunn Thanks!

**Comment by mgolfieri** [comment]
Thanks!

**Pull request merged**
